---

#########################################################################################
#                                                                                       #
##  Ansible playbook for providing two running and configured EC2 webserver instances  ##
#                                                                                       #
#########################################################################################

## Providing two running EC2 webserver instances
- hosts: local
  connection: local
  gather_facts: False
  roles:
    - common

## Installation and configuration on EC2 webserver instances
- hosts: webservers
  remote_user: ec2-user
  become: yes
  gather_facts: False
  roles:
    - webservers
